GET http://localhost:8080/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hhb24gQWhtZWQiLCJ1c2VJZCI6IjY2ZGQwNTFiZmExMDA4NTkwMjhlMDI2MiIsImlhdCI6MTcyNjc1MzgyNSwiZXhwIjoxNzI2NzYxMDI1fQ.O2XQxxMVnwy2259XV50gVEoOlvwKcdzxx0PBREHYcYw

###
GET http://localhost:8080/api/v1/product/66dd0c557f943f5363b732fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hhb24gQWhtZWQiLCJ1c2VJZCI6IjY2ZGQwNTFiZmExMDA4NTkwMjhlMDI2MiIsImlhdCI6MTcyNjA1NDg5MCwiZXhwIjoxNzI2MDYyMDkwfQ.GCp6Km9uBjUBtZo4zrfdFEFFf2IW5RH-YiFUgilGQNM


###
POST  http://localhost:8080/api/v1/product/store
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hhb24gQWhtZWQiLCJ1c2VJZCI6IjY2ZGQwNTFiZmExMDA4NTkwMjhlMDI2MiIsImlhdCI6MTcyNjA1NDg5MCwiZXhwIjoxNzI2MDYyMDkwfQ.GCp6Km9uBjUBtZo4zrfdFEFFf2IW5RH-YiFUgilGQNM

{
    "product_name":"product 3",
    "product_price":22,
    "product_quantity":100,
    "product_brand":"brand 4",
    "product_category":"category 4",
    "product_description":"This is the product 4"
}

###
DELETE  http://localhost:8080/api/v1/product/66dd0c557f943f5363b732fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hhb24gQWhtZWQiLCJ1c2VJZCI6IjY2ZGQwNTFiZmExMDA4NTkwMjhlMDI2MiIsImlhdCI6MTcyNjA1NDg5MCwiZXhwIjoxNzI2MDYyMDkwfQ.GCp6Km9uBjUBtZo4zrfdFEFFf2IW5RH-YiFUgilGQNM

###

PATCH  http://localhost:8080/api/v1/product/66dd0c687f943f5363b732fc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hhb24gQWhtZWQiLCJ1c2VJZCI6IjY2ZGQwNTFiZmExMDA4NTkwMjhlMDI2MiIsImlhdCI6MTcyNjc1MzgyNSwiZXhwIjoxNzI2NzYxMDI1fQ.O2XQxxMVnwy2259XV50gVEoOlvwKcdzxx0PBREHYcYw


{
    "product_name":"product updated",
    "product_price":20,
    "product_quantity":100,
    "product_brand":"brand 1",
    "product_category":"category 1",
    "product_description":"This is the product 1"
}


###

POST http://localhost:8080/api/v1/sign-up
Content-Type: application/json

{
    "name":"Shaon Ahmed",
    "email":"shaon@gmail.com",
    "password":"123456"
}


###

POST http://localhost:8080/api/v1/sign-in
Content-Type: application/json

{
    "email":"shaon@gmail.com",
    "password":"123456"
}